### ISSUE TITLE
Allow a port, and allow import of data

### ISSUE THREAD

**Issue by pjnorris** [matt-FFFFFF/hassio-addon-teslamate#18]
Hey Matt, great add-on thanks.

Would it be possible to expose or have the option to expose an external port, so that I can access TeslaMate directly from a url, without going via Hass?

Furthermore, could you permit access to a folder, eg: /share/teslamate so I can put the 'import' folder in there to import teslafi data?
Thanks in advance.
Paul

**Comment by matt-FFFFFF** [comment]
Hi,

Thanks for the comments. I will look into access to the `/share` volume. Should be pretty easy, though permissions might be a small challenge.

As for direct access to the addon, can you expand on the specific use case? I'm interested in learning more about why direct access is required. As part of the recent update, changes were made to the app to make it work behind the nginx reverse proxy. These changes will break direct access using a published port. Therefore, looking to understand what the rationale is here.

Thanks

**Comment by matt-FFFFFF** [comment]
@pjnorris can you supply me an anonymised teslafi CSV file so that I can test the import process please? I do not use the service so can't access it.

**Comment by pjnorris** [comment]
[TeslaFi122020.csv.zip](https://github.com/matt-FFFFFF/hassio-addon-teslamate/files/5820144/TeslaFi122020.csv.zip)
Thanks Matt, Paul.

**Comment by pjnorris** [comment]
I have nginx running on Hass as well, use it to direct to pages etc. I wanted a clean interface of Teslafi, so I could access it by putting the HASS ip, eg: 192.168.1.2:4000 and will load it. Similar to what grafana does with port 3000, and Postgres does with 5432. 

Thanks

**Comment by matt-FFFFFF** [comment]
Re: Ingress

When I mention nginx, I'm not talking about the HA addon, I'm talking about another instance, inside the TeslaMate container. This is required because the HA supervisor generates a dynamic URL path for ingress.

The actual TeslaMate application is reconfigured to work with this new path in a startup script. See script below:

https://github.com/matt-FFFFFF/hassio-addon-teslamate/blob/641060f0cc66c2430865c091c972e05944a7e636/services/teslamate/run#L1-L11

The `sed` command modifies the TeslaMate configuration to work with the dynamic path. Now, because of this the application won't listen properly on `http://0.0.0.0:4000/`, as instead it will be something like `http://0.0.0.0/api/hassio_ingress/{INGRESSTOKEN}/`

This presents a problem with bypassing the ingress route as you won't know what the path is. Now, we could bypass the application reconfiguration with a configuration parameter, but I don't really want to do this as it's confusing for the end user as the addon states that it supports ingress in the `config.json`.

If you are logged into HA then accessing the addon is simple with a direct link - this URL won't change as the slug is based on the GitHub repo:

`http[s]://1.2.3.4/29b65938_teslamate`

**Comment by pjnorris** [comment]
Thanks Matt, understood. Yes I have used the URL used above, just has the HASS gui on. I can live with that 👍

**Comment by matt-FFFFFF** [comment]
Fixed in [v0.6.0](https://github.com/matt-FFFFFF/hassio-addon-teslamate/releases/tag/v0.6.0)
