### ISSUE TITLE
Question: is it possible to export all data and import to another container?

### ISSUE THREAD

**Issue by nijixuchao** [matt-FFFFFF/hassio-addon-teslamate#48]
I know official Testlamate has export and import feature, but I'm not sure how to run that within HA add-on. Is it possible to export the data the same way as official Teslamate does and import to another Teslamate container?

**Comment by matt-FFFFFF** [comment]
The addon has read/write access to `/share`. This location can be used to export the data.

**Comment by raforo** [comment]
> The addon has read/write access to `/share`. This location can be used to export the data.

I've made an Teslamate official backup in other system and I have the file teslamate.bck.
Can I import this old data in your add-on?
Oficial restore requires docker-compose instaled and a docker-Compose.yml file in the folder, but  I think HAOS don't use docker-compose.
Thanks and help

**Comment by raforo** [comment]
I've managed to install docker-compose on Home Assistant OS 2021.12.10 with:
sudo curl -L --fail https://github.com/docker/compose/releases/download/1.29.2/run.sh -o /usr/local/bin/docker-compose

But when I try to restore backup by offical way:
docker-compose exec -T database psql -U teslamate -d teslamate < teslamate.bck.

It gets error, because the official Docker-compose.yml file contains information about images and volumes that are different from the ones used on add-on.

Is there a way to import official backup data into the add-on?

Thanks for you help

**Comment by matt-FFFFFF** [comment]
You have shell access, so you could enter the container using `docker exec` instead of docker-compose.

You will need to place the database backup file on a volume that can be read by the container.

The container names can be listed by running `docker ps`

You will need an elevated shell for this, I use the SSH & Web Terminal addon with protection mode disabled, giving me full access to the system.

**Comment by raforo** [comment]
> You have shell access, so you could enter the container using `docker exec` instead of docker-compose.
> 
> You will need to place the database backup file on a volume that can be read by the container.
> 
> The container names can be listed by running `docker ps`
> 
> You will need an elevated shell for this, I use the SSH & Web Terminal addon with protection mode disabled, giving me full access to the system.

Thanks for your answer. 

I've managed execute docker exec command outside the docker and psql comands inside the docker, but I can't pass the teslamate.bkn file inside the  postgres's volume.

Your Postgres Add-on create these volumes:
Host/volume	Path in container
/dev	/dev
/mnt/data/supervisor/addons/data/29b65938_postgres	/data

When I try to copy teslamate.bkn file to /dev folder Home Assistant OS cancel it saying System file is read only.
Finaly  /data folder, it seem not conectect to Volume and it can acces to backup file.
/mnt/data/supervisor/addons/data/29b65938_postgres doesn't exist.

Thanks

**Comment by matt-FFFFFF** [comment]
Hi,

If you're running this from the postgres container then that doesn't have access to /share.

I can update it so that it does.

**Comment by nijixuchao** [comment]
So I didn't find out how to export from cl, what I eventually did was to install a pgAdmin add-on so I can backup and export from there

**Comment by Chimpepe** [comment]
Can someone provide step by step instructions on how to export the data so that I can import it again in the standalone version?
